# Generated by Django 4.2.11 on 2025-07-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savedate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
