# Generated by Django 5.2.4 on 2025-08-01 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('price', models.FloatField()),
                ('price_range_low', models.FloatField(blank=True, null=True)),
                ('price_range_high', models.FloatField(blank=True, null=True)),
                ('url', models.URLField(null=True)),
                ('thumbnail_base', models.FileField(null=True, upload_to='')),
                ('thumbnail', models.FileField(null=True, upload_to='')),
                ('slug', models.CharField(max_length=255)),
                ('number_requested', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('claimed_gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.gift')),
            ],
        ),
    ]
