# Generated by Django 5.2.4 on 2025-08-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gift',
            name='thumbnail_base',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
