# Generated by Django 5.2.4 on 2025-08-01 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_gift_thumbnail_alter_gift_thumbnail_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
