# Generated by Django 5.2.4 on 2025-08-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_claim_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
